### ISSUE TITLE
can't find file sphereone.fds

### ISSUE THREAD

**Issue by GenB31415** [ToniaDemchuk/EMSimulation#3]
Please provide a file 'sphereone.fds' that is required in 'private static MeshInfo getMeshInfo()' . Thanks.

**Comment by ToniaDemchuk** [comment]
Hi,
Thank you for your feedback.

The file with input data for object were added - sphere.fds in this commit https://github.com/ToniaDemchuk/EMSimulation/commit/61f42176f56e82ebd4a186b2394d995bc3460e74.
Make sure you merge master branch with correct example path.
